name: PR Build Python

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # .x is semantic version syntax to get the latest minor release.

      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install any dependencies you need here, can use requirements.txt or just name packages

      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          click-to-expand: true
          report-title: 'Test Report'

      # create a test summary markdown file
      # if you don't specify an output file, it will automatically add
      # as a job summary. If you specify an output file, you have to
      # create your own step of adding it to the job summary. I am
      # intentionally doing that to show job summaries
      # - name: Create test summary
      #   uses: test-summary/action@v2.4
      #   with:
      #     paths: ${{ github.workspace }}/results/*.xml
      #     output: ${{ github.workspace }}/results/summary.md
      #     show: "all"
      #   if: always()

      # # I am adding the test results to the Job Summary
      # - name: Add Test Results To Job Summary
      #   run: |
      #     echo "TEST RESULTS:" >> $GITHUB_STEP_SUMMARY
      #     echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
      #     cat "${{ github.workspace }}/results/summary.md" >> $GITHUB_STEP_SUMMARY
      #   if: always()
